
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/don404/Qt/Tools/CMake/share/cmake-3.30/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The target system is: Android - 1 - aarch64
      The host system is: Linux - 6.18.15-400.asahi.fc43.aarch64+16k - aarch64
...
